version: "3.8"

services:
  redwood-app:
    image: node:20-bookworm-slim
    container_name: redwood-app
    working_dir: /app
    volumes:
      - .:/app
      # mount the ./api/db/schema.prisma file to the container
      - ./api/db/schema.prisma:/app/prisma/schema.prisma
    ports:
      - "8910:8910" # Redwood Web
      - "8911:8911" # Redwood API
      - "5555:5555" # Redwood Prisma Studio
      - "4318:4318" # Redwood Studio
      - "7910:7910" # Redwood Storybook
    environment:
      BROWSER: "none"
      NODE_ENV: ${NODE_ENV:-development} # Default to development if not set
    entrypoint: |
      bash -c "
      apt-get update && apt-get install -y openssl libssl3 ca-certificates yarn &&
      yarn config set --home Telemetry 0
      yarn install --yes &&
      corepack enable &&
      corepack prepare yarn@stable --activate &&
      if [ \"$NODE_ENV\" = \"production\" ]; then
        yarn install --yes &&
        if [ ! -f /app/prisma/schema.prisma ]; then
          echo 'Prisma schema not found. Skipping prisma generate.';
        #if [ ! -f /app/api/db/schema.prisma ]; then
        #  echo 'Prisma schema not found. Skipping prisma generate.';
        else
          npx prisma generate --schema=/app/prisma/schema.prisma;
        fi &&
        yarn rw build &&
        yarn rw serve;
      else
        if [ ! -f /app/redwood.toml ]; then
          echo '{\"private\": true}' > /app/package.json &&
          echo 'n\n' | yarn create redwood-app . --force --no-typescript --overwrite;
        fi &&
        yarn install --yes &&
        rm -rf node_modules/.prisma &&
        npx prisma generate &&
        yarn rw dev;
      fi
      "
    restart: unless-stopped

volumes:
  redwood-data:
