
version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  
  api:
    image: node:14  # or a specific version you prefer
    restart: always
    volumes:
      - ./api:/app/api  # Mount your local api directory
    working_dir: /app/api
    command: sh -c "yarn install && yarn rw dev"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDWOOD_ENV: development
    depends_on:
      - db

  web:
    image: node:14  # or a specific version you prefer
    restart: always
    volumes:
      - ./web:/app/web  # Mount your local web directory
    working_dir: /app/web
    command: sh -c "yarn install && yarn rw dev"
    ports:
      - "8910:8910"
    environment:
      API_URL: http://api:YOUR_API_PORT  # Insert the correct port if necessary
    depends_on:
      - api

volumes:
  db_data:

networks:
  default:
