version: "3.8"

services:
  redwood-app:
    image: node:20-bookworm-slim
    container_name: redwood-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8910:8910"
      - "8911:8911"
    entrypoint: 
      - sh
      - -c
      - |
        # Install dependencies
        apt-get update && apt-get install -y openssl libssl3 ca-certificates yarn &&

        # Initialize Redwood if not already present
        if [ ! -f /app/redwood.toml ]; then
          # Create a basic package.json with 'private' set to true
          echo '{
            "name": "redwood-app",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "dev": "rw dev",
              "build": "rw build",
              "start": "rw start",
              "generate": "rw generate"
            },
            "dependencies": {
              "@redwoodjs/api": "^0.20.0",
              "@redwoodjs/web": "^0.20.0",
              "prisma": "^4.10.0"
            }
          }' > /app/package.json &&
          yarn create redwood-app . --force --no-typescript --overwrite;
        fi

        # Install dependencies and generate Prisma
        yarn install --yes &&
        rm -rf node_modules/.prisma &&
        npx prisma generate &&

        # Enable Corepack for Yarn 3
        corepack enable &&

        # Start Redwood development server
        yarn rw dev
