version: "3.8"

services:
  redwood-app:
    image: node:20-bookworm-slim
    container_name: redwood-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8910:8910" # Redwood Web
      - "8911:8911" # Redwood API
    environment:
      BROWSER: "none"
      NODE_ENV: "production"
    entrypoint: |
      bash -c "
      apt-get update && apt-get install -y openssl libssl3 ca-certificates &&
      corepack enable &&
      yarn install &&
      if [ ! -f /app/prisma/schema.prisma ]; then
        echo 'Prisma schema not found. Skipping prisma generate.';
      else
        npx prisma generate --schema=/app/prisma/schema.prisma;
      fi &&
      yarn rw build &&
      yarn rw serve
      "
    restart: unless-stopped

volumes:
  redwood-data:
