version: "3.8"

services:
  redwood-app:
    image: node:20-bookworm-slim
    container_name: my-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8910:8910"
      - "8911:8911"
    command: sh
