version: "3.8"

services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      BROWSER: none
    command: bash -c "yarn create redwood-app . --no-typescript --no-install --overwrite --database sqlite  --no-git && corepack enable && corepack prepare yarn@stable --activate && yarn install && yarn redwood dev"
    ports:
      - "5555:5555"
      - "8911:8911"
      - "8910:8910"
      - "4318:4318"
      - "7910:7910"
