name: Build and Deploy Docker Image

on:
  push:
    branches:
      - build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: docker-compose -f docker-compose.yml up -d

    - name: Commit Docker Image
      run: |
        CONTAINER_ID=$(docker ps -aqf "name=redwood-app")
        docker commit $CONTAINER_ID ghcr.io/mbahrsnc/redwood-docker/redwood:latest
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push ghcr.io/mbahrsnc/redwood-docker/redwood:latest
