name: Build, Push, and Deploy using Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build Docker Images
      run: docker-compose -f docker-compose.yml build

    - name: Push Docker Images
      run: |
        docker tag redwood-app ghcr.io/${{ github.repository }}/redwood:latest
        docker push ghcr.io/${{ github.repository }}/redwood:latest

    - name: Deploy with Docker Compose
      run: docker-compose up -d
